### ISSUE TITLE
Does this handle plugins assets?

### ISSUE THREAD

**Issue by abimaelmartell** [acarbone/AssetsMinify#25] opened 2014-11-13 01:29 UTC
I just installed this and is not compressing woocommerce assets.

Do i need any extra configuration?

**Comment by acarbone** [comment] 2015-04-13 12:07
Will be fixed in the next release of the plugin. Currently on dev branch

**Closed by acarbone** 2015-04-13 12:07 UTC

**Comment by NickIvanter** [comment] 2015-07-26 19:20
I'm still having this issue, even with the latest release (2.0.2) that was supposed to address it. The WooComemrce CSS files are not combined and instead included as usual. 

The cause of the problem seems to be that WooCommerce uses protocol-relative URLs for its assets, i.e. omitting the http/https part of the URL. If I change WooCommerce not to remove the http/https from the assets' URLs, AssetsMinify begins to handle them as appropriate.

Update: I've found that this only happens on my https site. So, it's a combination of two factors: 1) protocol-relative asset URLs and 2) serving the website via HTTPS.

This change fixes it for me: https://github.com/acarbone/AssetsMinify/commit/71dd07c5a83b7ef1b2053cd9dd989265fa5aafb5
